// *****************************************************************************
//
// Copyright (c) 2026, Southwest Research Institute® (SwRI®)
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the Southwest Research Institute® (SwRI®) nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// *****************************************************************************

// Generated by tools/generate_raw_msgs.py. Do not edit.
#ifndef GPSD_CLIENT__GPSD_RAW_MESSAGE_HPP_
#define GPSD_CLIENT__GPSD_RAW_MESSAGE_HPP_

// GPSD_RAW_MESSAGE_NAME names the selected message for log output, so
// an operator can see which version was compiled in without guessing.
//
// gps.h defines STATUS_* macros that collide with the ROS message
// constants, so a message header must never be parsed after it. Every
// branch below includes its messages before gps.h is reached.
#include <gps.h>

#if GPSD_API_MAJOR_VERSION < 9
// cppcheck does not read gps.h, so it takes the version as 0.
// cppcheck-suppress preprocessorErrorDirective
#error "gpsd_client requires GPSd API version >= 9 (GPSd >= 3.20)"
#endif

#if GPSD_API_MAJOR_VERSION == 9 && GPSD_API_MINOR_VERSION == 0
#define GPSD_RAW_FILL_MAJOR 9
#define GPSD_RAW_FILL_MINOR 0
#elif GPSD_API_MAJOR_VERSION == 9 && GPSD_API_MINOR_VERSION == 1
#define GPSD_RAW_FILL_MAJOR 9
#define GPSD_RAW_FILL_MINOR 1
#elif GPSD_API_MAJOR_VERSION == 10 && GPSD_API_MINOR_VERSION == 0
#define GPSD_RAW_FILL_MAJOR 10
#define GPSD_RAW_FILL_MINOR 0
#elif GPSD_API_MAJOR_VERSION == 10 && GPSD_API_MINOR_VERSION == 1
#define GPSD_RAW_FILL_MAJOR 10
#define GPSD_RAW_FILL_MINOR 1
#elif GPSD_API_MAJOR_VERSION == 11 && GPSD_API_MINOR_VERSION == 0
#define GPSD_RAW_FILL_MAJOR 11
#define GPSD_RAW_FILL_MINOR 0
#elif GPSD_API_MAJOR_VERSION == 12 && GPSD_API_MINOR_VERSION == 0
#define GPSD_RAW_FILL_MAJOR 12
#define GPSD_RAW_FILL_MINOR 0
#elif GPSD_API_MAJOR_VERSION == 13 && GPSD_API_MINOR_VERSION == 0
#define GPSD_RAW_FILL_MAJOR 13
#define GPSD_RAW_FILL_MINOR 0
#elif GPSD_API_MAJOR_VERSION == 14 && GPSD_API_MINOR_VERSION == 0
#define GPSD_RAW_FILL_MAJOR 14
#define GPSD_RAW_FILL_MINOR 0
#elif GPSD_API_MAJOR_VERSION == 16 && GPSD_API_MINOR_VERSION == 0
#define GPSD_RAW_FILL_MAJOR 16
#define GPSD_RAW_FILL_MINOR 0
#elif GPSD_API_MAJOR_VERSION == 16 && GPSD_API_MINOR_VERSION == 1
#define GPSD_RAW_FILL_MAJOR 16
#define GPSD_RAW_FILL_MINOR 1
#else
// Newer than anything this generator knows about. Use the newest
// available message; its fields are a subset of what the build's
// gps.h declares, and every generated assignment is member-guarded,
// so this compiles -- it just cannot carry members added later.
#warning "Untested GPSd API version; falling back to the API 16.1 raw message"
#define GPSD_RAW_FILL_MAJOR 16
#define GPSD_RAW_FILL_MINOR 1
#endif

#if GPSD_RAW_FILL_MAJOR == 9 && GPSD_RAW_FILL_MINOR == 0
#include <gpsd_client/parsers/generated/gpsd_raw_fill_9v0.hpp>
#define GPSD_RAW_MESSAGE_NAME "GPSDRaw9v0"
namespace gpsd_client
{
using GpsdRawMsg = gps_msgs::msg::GPSDRaw9v0;
}  // namespace gpsd_client
#elif GPSD_RAW_FILL_MAJOR == 9 && GPSD_RAW_FILL_MINOR == 1
#include <gpsd_client/parsers/generated/gpsd_raw_fill_9v1.hpp>
#define GPSD_RAW_MESSAGE_NAME "GPSDRaw9v1"
namespace gpsd_client
{
using GpsdRawMsg = gps_msgs::msg::GPSDRaw9v1;
}  // namespace gpsd_client
#elif GPSD_RAW_FILL_MAJOR == 10 && GPSD_RAW_FILL_MINOR == 0
#include <gpsd_client/parsers/generated/gpsd_raw_fill_10v0.hpp>
#define GPSD_RAW_MESSAGE_NAME "GPSDRaw10v0"
namespace gpsd_client
{
using GpsdRawMsg = gps_msgs::msg::GPSDRaw10v0;
}  // namespace gpsd_client
#elif GPSD_RAW_FILL_MAJOR == 10 && GPSD_RAW_FILL_MINOR == 1
#include <gpsd_client/parsers/generated/gpsd_raw_fill_10v1.hpp>
#define GPSD_RAW_MESSAGE_NAME "GPSDRaw10v1"
namespace gpsd_client
{
using GpsdRawMsg = gps_msgs::msg::GPSDRaw10v1;
}  // namespace gpsd_client
#elif GPSD_RAW_FILL_MAJOR == 11 && GPSD_RAW_FILL_MINOR == 0
#include <gpsd_client/parsers/generated/gpsd_raw_fill_11v0.hpp>
#define GPSD_RAW_MESSAGE_NAME "GPSDRaw11v0"
namespace gpsd_client
{
using GpsdRawMsg = gps_msgs::msg::GPSDRaw11v0;
}  // namespace gpsd_client
#elif GPSD_RAW_FILL_MAJOR == 12 && GPSD_RAW_FILL_MINOR == 0
#include <gpsd_client/parsers/generated/gpsd_raw_fill_12v0.hpp>
#define GPSD_RAW_MESSAGE_NAME "GPSDRaw12v0"
namespace gpsd_client
{
using GpsdRawMsg = gps_msgs::msg::GPSDRaw12v0;
}  // namespace gpsd_client
#elif GPSD_RAW_FILL_MAJOR == 13 && GPSD_RAW_FILL_MINOR == 0
#include <gpsd_client/parsers/generated/gpsd_raw_fill_13v0.hpp>
#define GPSD_RAW_MESSAGE_NAME "GPSDRaw13v0"
namespace gpsd_client
{
using GpsdRawMsg = gps_msgs::msg::GPSDRaw13v0;
}  // namespace gpsd_client
#elif GPSD_RAW_FILL_MAJOR == 14 && GPSD_RAW_FILL_MINOR == 0
#include <gpsd_client/parsers/generated/gpsd_raw_fill_14v0.hpp>
#define GPSD_RAW_MESSAGE_NAME "GPSDRaw14v0"
namespace gpsd_client
{
using GpsdRawMsg = gps_msgs::msg::GPSDRaw14v0;
}  // namespace gpsd_client
#elif GPSD_RAW_FILL_MAJOR == 16 && GPSD_RAW_FILL_MINOR == 0
#include <gpsd_client/parsers/generated/gpsd_raw_fill_16v0.hpp>
#define GPSD_RAW_MESSAGE_NAME "GPSDRaw16v0"
namespace gpsd_client
{
using GpsdRawMsg = gps_msgs::msg::GPSDRaw16v0;
}  // namespace gpsd_client
#elif GPSD_RAW_FILL_MAJOR == 16 && GPSD_RAW_FILL_MINOR == 1
#include <gpsd_client/parsers/generated/gpsd_raw_fill_16v1.hpp>
#define GPSD_RAW_MESSAGE_NAME "GPSDRaw16v1"
namespace gpsd_client
{
using GpsdRawMsg = gps_msgs::msg::GPSDRaw16v1;
}  // namespace gpsd_client
#endif

#endif  // GPSD_CLIENT__GPSD_RAW_MESSAGE_HPP_
